FROM ubuntu:18.04

RUN apt-get update && apt-get install npm -y
RUN npm install -g serve
COPY aws-app /opt/aws-app

WORKDIR /opt/aws-app
RUN npm install
RUN npm run build

CMD [ "serve", "-s", "build" ]

EXPOSE 3000 9000