FROM ubuntu:18.04

RUN apt-get update && apt-get install npm -y
RUN npm install -g serve
COPY aws-app /opt/aws-app

WORKDIR /opt/aws-app
RUN npm install
RUN npm run build

CMD [ "serve", "-s", "build", "--", "--port", "80" ]
# CMD [ "npm", "start", "--", "--port", "80" ]

EXPOSE 5000 9000